title: MosBlog
description: 车和不是车的自存处
author: 玟梓（KAOKOS）
avatar: /logo.png
email: EvanChen99@outlook.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
skin: freestyle

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: 
logo: https://ftp.bmp.ovh/imgs/2021/03/d2499449ece9977a.png
social:
  name: 玟梓
  links:
    - https://weibo.com/u/2132057051/home?wvr=5
    - https://www.lofter.com/blog/mosquitoyeah?act=dashboardclick_20130514_04
    - https://github.com/Snaky9/SBlog
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
#comment